Platform-OS/pos-module-components

.gitignore
public/assets/components.css
public/assets/styleguide.js
public/views/pages/styleguide.liquid
public/views/partials/lib/queries/get_components.liquid

Component override support for the style guide
Show implementation (component partial path) in the styleguide for each component
https://trello.com/c/wpCtU3MZ

Styleguide override handling & implementation details

---

public/views/partials/atoms/card.liquid
src/colors.default.js
src/tailwind.config.js

- Updated the paddings
- Added custom shadow in the config (I have no idea what was the plan to do it better, probably will need some thinking)
- Talked with Gyöngy but we have a problem identifying what was the need for 'highlighted' card and settled that this is should be for the sections that are marked with color that are inside the cards.
- Moved the color definitions in Tailwind config in a order they appear in Figma
https://trello.com/c/cTus3MFT/52-card

Updated the card component to match Figma

---

public/views/partials/atoms/card.liquid
src/colors.default.js
src/tailwind.config.js

Tailwind is a shitty software so you can't name the variables as you want as they will be mixed up. 🤷‍♂️

Fixed shadow declaration not to mix with color

---

.gitignore

Added generated assets to gitignore

Adding assets to gitignore

---

public/views/partials/atoms/button.liquid

- Updated every size to 1:1 match Figma
https://trello.com/c/8lvKwzZN/55-button

Button updates

---

public/views/partials/atoms/input.liquid

Input improvements based on review at https://trello.com/c/KxTdaZ0b/54-input
https://trello.com/c/KxTdaZ0b/54-input

Input fields improvements

---

README.md
public/views/pages/index.liquid
public/views/pages/show.liquid
public/views/partials/lib/hooks/hook_admin_menu.liquid
public/views/partials/lib/hooks/hook_permission.liquid

Use authorization
https://trello.com/c/DwAUaLvD/31-use-access-control-for-all-modules-authorization

Authorization

---

.editorconfig
README.md

First version of the contributor guidelines.
https://trello.com/c/X3Mw1Kuj
https://trello.com/c/A1SNxgrX

Contributor guidelines WIP

---

public/views/layouts/styleguide.html.liquid
public/views/partials/atoms/button.liquid
public/views/partials/atoms/checkbox.liquid
public/views/partials/molecules/select.liquid
src/components.js
src/scripts/components/select.js
src/styles/components.css
src/styles/components/select.css

https://trello.com/c/AUx0r9WM/58-select

Select component

---

public/views/pages/colors.liquid
public/views/partials/molecules/iconbutton.liquid
src/colors.default.js
src/tailwind.config.js

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Theme settings & editor

---

public/views/partials/atoms/card.liquid

https://platformos.slack.com/archives/C0445DJ9ECU/p1666079935113139

Printing card content

---

public/views/partials/molecules/alert.liquid

https://trello.com/c/HNphQcut/65-alert

Alert component

---

public/views/partials/atoms/badge.liquid
public/views/partials/molecules/icon-with-badge.liquid

https://trello.com/c/cOnac5w3/173-badge

Badge, Icon with badge

---

README.md
changelog-template.hbs
package-lock.json
package.json
public/views/partials/lib/hooks/hook_module_info.liquid
template-values.json

Add versioning support

---

public/views/partials/atoms/review-bar.liquid

https://trello.com/c/pYGa9UVG/180-review-bar
https://og-golden-qa.staging.oregon.platform-os.com/styleguide/31074900

Review bar

---

public/views/partials/atoms/card.liquid
public/views/partials/organisms/content-card.liquid
src/tailwind.config.js

https://trello.com/c/CLf8hzSg/184-blog-card
https://og-golden-poc.staging.oregon.platform-os.com/styleguide/31328503

Content card

---

public/views/partials/atoms/avatar.liquid

https://trello.com/c/iHUGSaip/205-avatar-component-update-sizes
https://og-golden-poc.staging.oregon.platform-os.com/styleguide/30821465

New avatar sizes

---

public/views/partials/molecules/status-label.liquid

https://trello.com/c/7J9PBCj5/202-status-label-component
https://og-golden-poc.staging.oregon.platform-os.com/styleguide/31626896

Status label

---

public/views/partials/molecules/view_more_less.liquid
src/components.js
src/scripts/components/more-less.js

https://og-golden-poc.staging.oregon.platform-os.com/styleguide/31778970

View more less

---

public/views/partials/organisms/content-card.liquid

New params for re-using this in organisms.

Content card new params

---

public/views/partials/atoms/checkbox.liquid
public/views/partials/lib/hooks/hook_headscripts.liquid
public/views/partials/molecules/formfield.liquid

formfield update to support select & checkbox; 
headscripts hook update to add js bundle

Components update

---

public/views/partials/molecules/select.liquid
src/scripts/components/select.js

Add scrollbar to select component dropdown
https://trello.com/c/QTrlTDzm/96-bug-add-scrollbar-to-select-component-dropdown

select scrolling fix

---

public/views/partials/atoms/avatar.liquid
public/views/partials/atoms/backdrop.liquid
public/views/partials/atoms/badge.liquid
public/views/partials/atoms/button.liquid
public/views/partials/atoms/card.liquid
public/views/partials/atoms/checkbox.liquid
public/views/partials/atoms/heading.liquid
public/views/partials/atoms/input.liquid
public/views/partials/atoms/radio.liquid
public/views/partials/atoms/review-bar.liquid
public/views/partials/atoms/sidenote.liquid
public/views/partials/atoms/tabs.liquid
public/views/partials/atoms/toggle.liquid
public/views/partials/molecules/accordion.liquid
public/views/partials/molecules/alert.liquid
public/views/partials/molecules/breadcrumbs.liquid
public/views/partials/molecules/chip.liquid
public/views/partials/molecules/formfield.liquid
public/views/partials/molecules/header-profile.liquid
public/views/partials/molecules/icon-with-badge.liquid
public/views/partials/molecules/iconbutton.liquid
public/views/partials/molecules/input-with-button.liquid
public/views/partials/molecules/pagination.liquid
public/views/partials/molecules/popup.liquid
public/views/partials/molecules/rating.liquid
public/views/partials/molecules/search-field.liquid
public/views/partials/molecules/select.liquid
public/views/partials/molecules/status-label.liquid
public/views/partials/molecules/view-more-less.liquid
public/views/partials/organisms/content-card.liquid

support for flat list of component params for every component
https://trello.com/c/pVDDd2Kf/103-cl-support-for-flat-list-of-component-params-for-every-component

Flat list component params

---

public/views/partials/_styleguide_components/sidebar.liquid
public/views/partials/_styleguide_components/view.liquid
public/views/partials/atoms/button.liquid
public/views/partials/atoms/input.liquid

Button tag fix; 
styleguide page improvements; 
add textarea support to input component

various fixes and small improvements

---

public/views/partials/organisms/content-card.liquid

- content card responsive images
- htmlsafe content

content card additions

---

public/views/partials/atoms/avatar.liquid
public/views/partials/atoms/button.liquid
public/views/partials/molecules/select.liquid

Avatar classlist fix
Select component: default value support for single- and multiselect

Component updates: button, select, avatar

---

public/views/partials/atoms/avatar.liquid
public/views/partials/atoms/button.liquid
public/views/partials/molecules/iconbutton.liquid

Avatar component classlist fix
button & iconbutton adjustments

Component adjustments

---

public/views/partials/atoms/heading.liquid
public/views/partials/atoms/input.liquid
public/views/partials/molecules/formfield.liquid

Add captcha; component updates

---

public/views/partials/atoms/backdrop.liquid

Add z-index to backdrop component

Backdrop z-index

---

public/views/partials/molecules/formfield.liquid

Add html support for formfield label

HTML support for formfield label

---

public/views/partials/atoms/input.liquid
public/views/partials/molecules/chip.liquid

chip attributes, textarea placeholder
https://trello.com/c/MVekg01m/188-activity-feed-visual-differences

chip attributes, textarea placeholder

---

public/views/partials/atoms/icon.liquid
public/views/partials/molecules/iconbutton.liquid
public/views/partials/molecules/select.liquid

Some enhancement for community group listing page.
https://trello.com/c/YtL3w8ez/218-group-listing-page-visual-differences

Select placeholder, messages icon

---

public/views/partials/molecules/select.liquid

Fix select component width & classes support

Select width

---

public/views/partials/molecules/formfield.liquid

Add an optional icon to the form field description. 
https://trello.com/c/VNxm1wW4/157-pcbs-edit-profile

Add optional icon to form field description

---

public/views/partials/molecules/pagination.liquid

https://trello.com/c/YtL3w8ez/218-group-listing-page-visual-differences

stroke color

---

public/views/partials/atoms/avatar.liquid

Avatar fix
https://trello.com/c/Wj8aNHvZ

Avatar image ratio fix

---

public/views/partials/molecules/accordion.liquid

Custom class support for the accordion component and making it responsive. 
Allow html content.
https://trello.com/c/D1TBdnFo

Accordion class fix

---

public/views/partials/organisms/content-card.liquid

a11y for the content card
https://trello.com/c/wqt5YoY7

Accessibility udpate

---

public/graphql/components/get_all.graphql
public/views/partials/_styleguide_components/sidebar.liquid
public/views/partials/_styleguide_components/view.liquid

Explicitly add an increased limit to the components/get_all query
Add `template` components
Error handling
--

Improvements

---

public/views/partials/molecules/header-profile.liquid

Responsive version of the header profile component
--

responsive header profile

---

public/views/partials/molecules/alert.liquid
public/views/partials/molecules/flashes.liquid

Added max-width to alert & flashes components
https://trello.com/c/3NtpTZzn

Flashes & alert max-width

---

public/views/partials/molecules/input-with-button.liquid

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

icon with button iPhone fix

---

public/views/partials/molecules/input-with-button.liquid

Button class fix for input-with-button
--

Fix button classes for input-with-button component

---

public/views/partials/organisms/content-card.liquid

Long  card title fix
https://trello.com/c/woW8vxy0/410-mobile-fixes

content card long title fix

---

public/views/partials/molecules/search-field.liquid

Rounded button styles fix.
https://trello.com/c/CTMWmZ3P/411-all-the-orange-search-buttons-are-misaligned

search field fix

---

public/views/partials/molecules/search-field.liquid

https://trello.com/c/Z5eDQVc2/387-formatting-needs-fixing

search field border on iPhone 13

---

public/views/partials/molecules/accordion.liquid

Allow lists inside accordion
necessary for:
https://trello.com/c/N5iq1g3z/74-faq-page

Allow lists inside accordion

---

public/views/partials/pages/403.liquid

Basic 403 page (can be styled in the scope of the parent project as a standard component override implementation)
https://trello.com/c/LAbENTUb

Add basic 403 page component

---

public/views/partials/molecules/flashes.liquid

Make flash notices more conspicuous.
https://trello.com/c/o7o5hvAM/87-wrong-password-ux-tweak

Move flash notices to top of the page

---

public/views/partials/atoms/avatar.liquid

Add data-avatar attr so avatar image uploader can automatically update it

add data-avatar attribute to avatar component

---

public/views/partials/molecules/dropdown.liquid

Fix z-index of dropdown menus
Part #3 of this card:
https://trello.com/c/NmmK3y9m/92-mobile-view-issues-iphone-latest-ios

Fix mix-up of dropdown menus with chat

---

public/views/partials/atoms/checkbox.liquid

Send default value for checkbox
needed for:
https://trello.com/c/d1OoehvN/440-as-a-user-i-want-to-be-able-to-hide-or-set-to-public-my-email-address-and-phone-number-on-my-edit-profile-page

Send default value for checkbox

---

modules/components/src/postcss.config.js
modules/components/template-values.json

Integrating changes from styleseeker

---

modules/components/public/views/partials/components/atoms/nav_card.liquid

A new nav_card component is created.
https://github.com/Platform-OS/pos-module-community/pull/483

Add nav_card component
